// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: internal/proto/services.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner *string `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Name  *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Type  *string `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
}

func (x *CreateBirdRequest) Reset() {
	*x = CreateBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBirdRequest) ProtoMessage() {}

func (x *CreateBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBirdRequest.ProtoReflect.Descriptor instead.
func (*CreateBirdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBirdRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *CreateBirdRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateBirdRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type CreateBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
}

func (x *CreateBirdReply) Reset() {
	*x = CreateBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBirdReply) ProtoMessage() {}

func (x *CreateBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBirdReply.ProtoReflect.Descriptor instead.
func (*CreateBirdReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBirdReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type GetBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner *string `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
}

func (x *GetBirdRequest) Reset() {
	*x = GetBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdRequest) ProtoMessage() {}

func (x *GetBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdRequest.ProtoReflect.Descriptor instead.
func (*GetBirdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *GetBirdRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

type GetBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner *string `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Name  *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Type  *string `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
}

func (x *GetBirdReply) Reset() {
	*x = GetBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBirdReply) ProtoMessage() {}

func (x *GetBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBirdReply.ProtoReflect.Descriptor instead.
func (*GetBirdReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *GetBirdReply) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *GetBirdReply) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetBirdReply) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type ChangeBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner *string `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
	Name  *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Type  *string `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
}

func (x *ChangeBirdRequest) Reset() {
	*x = ChangeBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBirdRequest) ProtoMessage() {}

func (x *ChangeBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBirdRequest.ProtoReflect.Descriptor instead.
func (*ChangeBirdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *ChangeBirdRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *ChangeBirdRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ChangeBirdRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type ChangeBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
}

func (x *ChangeBirdReply) Reset() {
	*x = ChangeBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeBirdReply) ProtoMessage() {}

func (x *ChangeBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeBirdReply.ProtoReflect.Descriptor instead.
func (*ChangeBirdReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeBirdReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type DeleteBirdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner *string `protobuf:"bytes,1,req,name=owner" json:"owner,omitempty"`
}

func (x *DeleteBirdRequest) Reset() {
	*x = DeleteBirdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBirdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBirdRequest) ProtoMessage() {}

func (x *DeleteBirdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBirdRequest.ProtoReflect.Descriptor instead.
func (*DeleteBirdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteBirdRequest) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

type DeleteBirdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string `protobuf:"bytes,1,req,name=message" json:"message,omitempty"`
}

func (x *DeleteBirdReply) Reset() {
	*x = DeleteBirdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_services_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBirdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBirdReply) ProtoMessage() {}

func (x *DeleteBirdReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_services_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBirdReply.ProtoReflect.Descriptor instead.
func (*DeleteBirdReply) Descriptor() ([]byte, []int) {
	return file_internal_proto_services_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBirdReply) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_internal_proto_services_proto protoreflect.FileDescriptor

var file_internal_proto_services_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x4c,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x51, 0x0a, 0x11,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x2b, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x8c, 0x02, 0x0a, 0x0b, 0x42, 0x69, 0x72, 0x64, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x72, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x40, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x72, 0x64, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x72, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x40, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x69, 0x72, 0x64, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_internal_proto_services_proto_rawDescOnce sync.Once
	file_internal_proto_services_proto_rawDescData = file_internal_proto_services_proto_rawDesc
)

func file_internal_proto_services_proto_rawDescGZIP() []byte {
	file_internal_proto_services_proto_rawDescOnce.Do(func() {
		file_internal_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_services_proto_rawDescData)
	})
	return file_internal_proto_services_proto_rawDescData
}

var file_internal_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_proto_services_proto_goTypes = []interface{}{
	(*CreateBirdRequest)(nil), // 0: proto.CreateBirdRequest
	(*CreateBirdReply)(nil),   // 1: proto.CreateBirdReply
	(*GetBirdRequest)(nil),    // 2: proto.GetBirdRequest
	(*GetBirdReply)(nil),      // 3: proto.GetBirdReply
	(*ChangeBirdRequest)(nil), // 4: proto.ChangeBirdRequest
	(*ChangeBirdReply)(nil),   // 5: proto.ChangeBirdReply
	(*DeleteBirdRequest)(nil), // 6: proto.DeleteBirdRequest
	(*DeleteBirdReply)(nil),   // 7: proto.DeleteBirdReply
}
var file_internal_proto_services_proto_depIdxs = []int32{
	0, // 0: proto.BirdService.CreateBird:input_type -> proto.CreateBirdRequest
	2, // 1: proto.BirdService.GetBird:input_type -> proto.GetBirdRequest
	4, // 2: proto.BirdService.ChangeBird:input_type -> proto.ChangeBirdRequest
	6, // 3: proto.BirdService.DeleteBird:input_type -> proto.DeleteBirdRequest
	1, // 4: proto.BirdService.CreateBird:output_type -> proto.CreateBirdReply
	3, // 5: proto.BirdService.GetBird:output_type -> proto.GetBirdReply
	5, // 6: proto.BirdService.ChangeBird:output_type -> proto.ChangeBirdReply
	7, // 7: proto.BirdService.DeleteBird:output_type -> proto.DeleteBirdReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_services_proto_init() }
func file_internal_proto_services_proto_init() {
	if File_internal_proto_services_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_services_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBirdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_services_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteBirdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_services_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_services_proto_goTypes,
		DependencyIndexes: file_internal_proto_services_proto_depIdxs,
		MessageInfos:      file_internal_proto_services_proto_msgTypes,
	}.Build()
	File_internal_proto_services_proto = out.File
	file_internal_proto_services_proto_rawDesc = nil
	file_internal_proto_services_proto_goTypes = nil
	file_internal_proto_services_proto_depIdxs = nil
}
